### ISSUE TITLE
using from npm

### ISSUE THREAD

**Issue by venturecommunism** [typeetfunc/rx-datascript#2]
For some reason, I'm able to run npm test and all tests pass but when I try to import datascript-mori, rx-datascript, etc. into another project packaged up for a client (for e.g. https://github.com/facebookincubator/create-react-app), I keep getting:

reportOrDb$.map is not a function

for example with q$ or entity$.

I'm also not able to get the "::" bind syntax work but I think that's a babel issue with my environment. I'm just doing:

try {
  let query = q$(parse(`[:find ?n ?q :where [?e "name" ?n] [?e "age" ?a]]`))
} catch (err) {
  console.log(err.message)
}

Do you have an example of this working in a browser?

**Comment by typeetfunc** [comment]
Thanks for report! Maybe you can provide repo with example?
`try {
let query = q$(parse([:find ?n ?q :where [?e "name" ?n] [?e "age" ?a]]))
} catch (err) {
console.log(err.message)
}`
First argument in q$ is reactive conn - see example - https://github.com/typeetfunc/rx-datascript/blob/master/test/index.spec.js#L16

**Comment by venturecommunism** [comment]
Unfortunately I nuked everything I had.

I've sort of concluded everything around datomic especially datomic itself is too poorly documented to do anything with for now.

This project is a strong effort though.

Maybe if hitchhiker trees get further along there'll be an open source clone to work from that can give projects like this the push they need.
